const products={
  "AE-M001":{name:"Urban Flame Oversized Tee",price:499,category:"MEN · OVERSIZED TEE",description:"A bold oversized streetwear tee with statement flame graphics and a relaxed everyday fit.",variants:[{colour:"White",sizes:["M","L","XL"],images:[]},{colour:"Black",sizes:["S","M","L","XL"],images:[]}]},
  "AE-M002":{name:"Shadow Bunny Oversized Tee",price:499,category:"MEN · OVERSIZED TEE",description:"A black oversized tee with a statement bunny-inspired graphic and an easy streetwear silhouette.",variants:[{colour:"Black",sizes:["S","M","L","XL"],images:[]}]},
  "AE-M003":{name:"Taurus Oversized Graphic Tee",price:499,category:"MEN · OVERSIZED TEE",description:"A powerful black oversized tee featuring a Taurus-inspired bull graphic with green accents.",variants:[{colour:"Black",sizes:["S","M","L","XL"],images:[]}]},
  "AE-M004":{name:"Heaven Made Oversized Tee",price:499,category:"MEN · OVERSIZED TEE",description:"A black oversized streetwear tee with gothic-inspired typography and statement artwork.",variants:[{colour:"Black",sizes:["S","M","L","XL"],images:[]}]},
  "AE-M005":{name:"Purple Chaos Oversized Tee",price:699,category:"MEN · OVERSIZED TEE",description:"A premium beige oversized tee with a striking purple statement graphic.",variants:[{colour:"Beige / Cream",sizes:["M","L","XL"],images:[]}]},
  "AE-M006":{name:"Heritage Premium Polo",price:899,category:"MEN · PREMIUM POLO",description:"ATTITUDE EMPIRE's No. 1 premium pick: a refined, relaxed polo with vintage-inspired streetwear character.",variants:[
    {colour:"Chocolate Brown / Cream",sizes:["M","L","XL"],images:[]},{colour:"White / Navy",sizes:["XL"],images:[]},{colour:"Black",sizes:["S","L","XL"],images:[]},{colour:"Beige / Brown",sizes:["S","M","L","XL","XXL"],images:[]},{colour:"Navy Blue / White",sizes:["S","L"],images:[]}
  ]},
  "AE-M007":{name:"Retro Stripe Knit Polo",price:699,category:"MEN · KNIT POLO",description:"A retro-inspired relaxed polo with bold cream and brown vertical stripes over a black base.",variants:[{colour:"Black / Cream / Brown",sizes:["S","M","L","XL","XXL"],images:[]}]},
  "AE-M008":{name:"Midnight Flow Dress",price:799,category:"WOMEN · DRESS",description:"An elegant statement dress with a clean upper silhouette and flowing layered design.",variants:[{colour:"Black",sizes:["S","M","L","XL"],images:["assets/ae-m008-black-1.png","assets/ae-m008-black-2.png"]},{colour:"Blush Pink",sizes:["S","M","L","XL"],images:["assets/ae-m008-blush-1.png"]}]},
  "AE-M009":{name:"Lavender Luxe Co-ord Set",price:699,category:"WOMEN · CO-ORD SET",description:"A sophisticated lavender co-ord with a relaxed collared top and matching trousers.",variants:[{colour:"Lavender / Lilac",sizes:["S","M"],images:["assets/ae-m009-1.png","assets/ae-m009-2.png","assets/ae-m009-3.png"]}]},
  "AE-M010":{name:"Mocha Elegance Co-ord Set",price:699,category:"WOMEN · CO-ORD SET",description:"A polished chocolate-brown co-ord featuring a flowing statement top and matching trousers.",variants:[{colour:"Chocolate Brown / Mocha",sizes:["S","M","L","XL"],images:["assets/ae-m010-1.png","assets/ae-m010-2.png","assets/ae-m010-3.png","assets/ae-m010-4.png"]}]}
};
let cart=[],activeProduct=null,activeVariant=0,activeSize="";
const cartDrawer=document.getElementById("cartDrawer"),overlay=document.getElementById("overlay"),cartItems=document.getElementById("cartItems"),cartCount=document.getElementById("cartCount"),cartTotal=document.getElementById("cartTotal"),searchPanel=document.getElementById("searchPanel"),searchInput=document.getElementById("searchInput"),mobileMenu=document.getElementById("mobileMenu"),productModal=document.getElementById("productModal");
function openCart(){cartDrawer.classList.add("active");overlay.classList.add("active")}
function closeLayers(){cartDrawer.classList.remove("active");productModal.classList.remove("active");overlay.classList.remove("active")}
document.getElementById("cartBtn").addEventListener("click",openCart);
document.getElementById("closeCart").addEventListener("click",closeLayers);
document.getElementById("closeProduct").addEventListener("click",closeLayers);
overlay.addEventListener("click",closeLayers);
document.querySelectorAll(".quick-add").forEach(button=>button.addEventListener("click",()=>openProduct(button.dataset.productId)));
function openProduct(id){activeProduct=id;activeVariant=0;activeSize="";const product=products[id];document.getElementById("modalName").textContent=product.name;document.getElementById("modalCategory").textContent=product.category;document.getElementById("modalCode").textContent=id;document.getElementById("modalDescription").textContent=product.description;document.getElementById("modalPrice").textContent="₹"+product.price.toLocaleString("en-IN");renderColours();renderVariant();productModal.classList.add("active");overlay.classList.add("active")}
function renderColours(){const wrap=document.getElementById("colourOptions");wrap.innerHTML="";products[activeProduct].variants.forEach((variant,index)=>{const button=document.createElement("button");button.textContent=variant.colour;button.className=index===activeVariant?"selected":"";button.addEventListener("click",()=>{activeVariant=index;activeSize="";renderColours();renderVariant()});wrap.appendChild(button)})}
function renderVariant(){const product=products[activeProduct],variant=product.variants[activeVariant],image=document.getElementById("modalImage"),thumbs=document.getElementById("modalThumbs"),sizes=document.getElementById("sizeOptions");const fallback=document.querySelector('[data-product-id="'+activeProduct+'"]').closest(".product-image").querySelector(".product-photo");image.src=variant.images[0]||(fallback?fallback.src:"");image.alt=product.name+" in "+variant.colour;image.classList.toggle("no-photo",!image.src);thumbs.innerHTML="";variant.images.forEach((src,index)=>{const button=document.createElement("button"),thumb=document.createElement("img");thumb.src=src;thumb.alt="View "+(index+1);button.appendChild(thumb);button.className=index===0?"selected":"";button.addEventListener("click",()=>{image.src=src;thumbs.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));button.classList.add("selected")});thumbs.appendChild(button)});sizes.innerHTML="";variant.sizes.forEach(size=>{const button=document.createElement("button");button.textContent=size;button.className=size===activeSize?"selected":"";button.addEventListener("click",()=>{activeSize=size;sizes.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));button.classList.add("selected")});sizes.appendChild(button)})}
document.getElementById("addSelected").addEventListener("click",()=>{if(!activeSize){alert("Please select a size.");return}const product=products[activeProduct],variant=product.variants[activeVariant];cart.push({code:activeProduct,product:product.name,price:product.price,colour:variant.colour,size:activeSize});updateCart();productModal.classList.remove("active");openCart()});
function updateCart(){cartCount.textContent=cart.length;if(!cart.length){cartItems.innerHTML='<p class="empty-cart">Your cart is empty.</p>';cartTotal.textContent="₹0";return}cartItems.innerHTML="";let total=0;cart.forEach((item,index)=>{total+=item.price;const div=document.createElement("div");div.className="cart-item";div.innerHTML='<div><h4>'+item.product+'</h4><p>'+item.code+" · "+item.colour+" · "+item.size+'</p><p>₹'+item.price.toLocaleString("en-IN")+'</p></div><button class="remove-item" data-index="'+index+'">REMOVE</button>';cartItems.appendChild(div)});cartItems.querySelectorAll(".remove-item").forEach(btn=>btn.addEventListener("click",()=>{cart.splice(Number(btn.dataset.index),1);updateCart()}));cartTotal.textContent="₹"+total.toLocaleString("en-IN")}
document.querySelectorAll(".wishlist").forEach(button=>button.addEventListener("click",()=>{button.classList.toggle("active");button.textContent=button.classList.contains("active")?"♥":"♡"}));
document.getElementById("searchBtn").addEventListener("click",()=>{searchPanel.classList.add("active");searchInput.focus()});
document.getElementById("closeSearch").addEventListener("click",()=>{searchPanel.classList.remove("active");searchInput.value="";filterProducts("")});
searchInput.addEventListener("input",()=>filterProducts(searchInput.value.toLowerCase()));
function filterProducts(search){document.querySelectorAll(".product-card").forEach(card=>{card.style.display=card.dataset.name.toLowerCase().includes(search)?"":"none"})}
document.getElementById("menuBtn").addEventListener("click",()=>mobileMenu.classList.toggle("active"));
document.querySelectorAll(".mobile-menu a").forEach(link=>link.addEventListener("click",()=>mobileMenu.classList.remove("active")));
document.getElementById("newsletterForm").addEventListener("submit",function(event){event.preventDefault();alert("Welcome to ATTITUDE EMPIRE!");this.reset()});
document.getElementById("checkoutBtn").addEventListener("click",()=>{if(!cart.length){alert("Your cart is empty.");return}alert("Checkout and secure online payment will be connected in the next stage.")});
updateCart();

